### ISSUE TITLE
Mrkvon was dismissed

### ISSUE THREAD

**Issue by chmac** [trustroots-community/trustrots#3]
@mrkvon was dismissed as a volunteer already in July 2022. Sorry it took so long to update GitHub to reflect that.

**Comment by mrkvon** [comment]
Can you provide evidence to support your claim? And elaborate on why and by whom?

How is it related to this repository?

**Comment by chmac** [comment]
It is related because it's a fact you omit from your history.

I don't need to provide you with any evidence, you were there.

**Comment by mrkvon** [comment]
> It is related because it's a fact you omit from your history.

I didn't receive any formal, authorized dismissal at that time. Please provide evidence proving contrary. Unfounded claims are not sufficient here.

Also, the timeline's focus is intentionally more generic, so it's unlikely such specific, personal events would be included.

> I don't need to provide you with any evidence, you were there.

Not that I'm aware of. This is referring to more than 1.5 years ago, so a reference would help here.

Closing this as unfounded and irrelevant. Happy to reopen if proven otherwise.

**Comment by chmac** [comment]
Did you ever receive a formal, authorised confirmation or invitation to volunteer?

You were dismissed in the same manner as you were recruited. Informally by the current site administrators.

You have no authorisation from the foundation, its directors, and no legal basis under which you can manage or control the site, services or user data.

Your claim / complaint seems to rest on your presumption of moral authority. You seem to believe that trustroots ought to follow the way of managing volunteers that Mikael practiced during his leadership. This is not written into the statutes of the foundation, and it's not the policy of the current site administrators. While I understand your *desire* for this to be the case, it simply is not, and there is no basis to claim otherwise.
